### ISSUE TITLE
"box-none" wont allow click through

### ISSUE THREAD

**Issue by biggeb4** [Charanor/react-native-highlight-overlay#3]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `react-native-highlight-overlay@1.2.1` for the project I'm working on. the reason is that "box-none" wasn't allowing click through, also a way for customizing the darkness of the backgound would be nice.
Great work.

Here is the diff that solved my problem:
--- a/node_modules/react-native-highlight-overlay/src/HighlightOverlay.tsx
+++ b/node_modules/react-native-highlight-overlay/src/HighlightOverlay.tsx
@@ -52,7 +52,7 @@ function HighlightOverlay({ highlightedElementId, onDismiss }: HighlightOverlayP
 			{highlightedElementData != null && parentSize != null && (
 				<Svg
 					style={StyleSheet.absoluteFill}
-					pointerEvents={clickThrough ? "box-none" : "auto"}
+					pointerEvents={clickThrough ? "none" : "auto"}
 					onPress={!clickThrough ? onDismiss : undefined}
 				>
 					<G>

**Comment by Charanor** [comment]
Hey! Thanks a lot for sharing this. If you want to PR this feel free, otherwise I'll publish a patch with this a bit later (crediting you ofc :) ).

Customization is definitely something that's lacking right now, I have a WIP branch up but I've been too busy with work and family to be able to publish anything substantial yet.

**Comment by carolinaknoll** [comment]
Hey there 👋 :blush: 

Would it be possible to publish a npm version with this fix? 

I am having a similar issue with my iOS emulator where `UIView` throws an error if `clickthroughHighlight` is set to `true`:

> UIView base class does not support pointerEvent value: box-none

I'm not sure if there are other values set to `box-none`, but it seems the emulator doesn't like them very much, haha 😅 

Thank you!

**Comment by Charanor** [comment]
Hey! I'm sorry I haven't been able to get back to you sooner, I haven't had time to work on this in my free time. I'm going to add a fix for the flickering in #7 and then I'll publish a new version :)

**Comment by Charanor** [comment]
1.3.0 has been released 🎉
